### ISSUE TITLE
Stubby fails to build

### ISSUE THREAD

**Issue by roglio** [thebiguno/microcontroller-projects#2]
Hi, I recently made a Stubby and I'm quite happy with him :)
There are some issue about power consumption but I count to fix it using a step-down dc-dc converter and a LiPo.

Btw, I discovered this repository with all your interesting projects and the first thing I tried was to compile the Stubby firmware but, this is the result: (see below).

Maybe this repository is a "work in progress" then is perfectly legitimate to have some issues, but maybe it works for you because there are some component that you have and are not present in the repository.

Thanks!

lzaccaria@debian:~/microcontroller-projects/projects/stubby/src$ make build
[AS]    lib/pwm/pwm.S
[CC]    util/math.c
[CC]    util/convert.c
[CC]    lib/twi/twi.c
[CXX]   hardware/magnetometer_HMC5883L.cpp
[CXX]   hardware/timer2.cpp
[CXX]   hardware/status.cpp
[CXX]   hardware/battery.cpp
[CXX]   hardware/servo.cpp
[CXX]   hardware/distance_HCSR04.cpp
[CXX]   gait/gait_tripod.cpp
[CXX]   types/Point.cpp
[CXX]   Leg.cpp
[CXX]   util/delays.cpp
util/delays.cpp: In function ‘void delay_ms(uint16_t)’:
util/delays.cpp:65:25: error: ‘MESSAGE_SEND_ACKNOWLEDGE’ was not declared in this scope
   protocol_send_message(MESSAGE_SEND_ACKNOWLEDGE, data, 1);
                         ^
util/delays.cpp:65:58: error: ‘protocol_send_message’ was not declared in this scope
   protocol_send_message(MESSAGE_SEND_ACKNOWLEDGE, data, 1);
                                                          ^
util/delays.cpp:72:25: error: ‘MESSAGE_SEND_COMPLETE’ was not declared in this scope
   protocol_send_message(MESSAGE_SEND_COMPLETE, data, 1);
                         ^
util/delays.cpp:72:55: error: ‘protocol_send_message’ was not declared in this scope
   protocol_send_message(MESSAGE_SEND_COMPLETE, data, 1);
                                                       ^
../../../build/avr.mk:163: recipe for target '/home/lzaccaria/microcontroller-projects/projects/stubby/src/build/./util/delays.o' failed
make: **\* [/home/lzaccaria/microcontroller-projects/projects/stubby/src/build/./util/delays.o] Error 1

**Comment by thebiguno** [comment]
Hi there,

The official, working Stubby repo is at https://github.com/thebiguno/stubby.  This one is very much a work in progress (I am in the middle of modifying it to support a new controller, and happen to be making some architectural changes at the same time).  Once it works I am going to move it to the other repo, but for now it will stay here so that I have access to my other libraries and such.

(Originally, Stubby *did* live in this repo; however people running Windows noted that git + symlinks + Windows fails horribly, and I use symlinks extensively in the makefile setup for this repo.  To fix it, I moved Stubby to a separate repo with copies of the libraries rather than symlinks.)

Cheers

**Comment by roglio** [comment]
Thank you!
Cheers,
Leandro.
